// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX-kaFQ-GlBqMMrGwvp4iSIkA8ADtfiDI',
    appId: '1:793281383562:ios:b58aeb8743564af00c7173',
    messagingSenderId: '793281383562',
    projectId: 'flutiq',
    storageBucket: 'flutiq.firebasestorage.app',
    iosBundleId: 'com.example.flutterQaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX-kaFQ-GlBqMMrGwvp4iSIkA8ADtfiDI',
    appId: '1:793281383562:ios:b58aeb8743564af00c7173',
    messagingSenderId: '793281383562',
    projectId: 'flutiq',
    storageBucket: 'flutiq.firebasestorage.app',
    iosBundleId: 'com.example.flutterQaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABkxD0aOLF0oUqCLOBe8RaP_6xf16urpA',
    appId: '1:793281383562:web:a0f5b7ebd47e4c070c7173',
    messagingSenderId: '793281383562',
    projectId: 'flutiq',
    authDomain: 'flutiq.firebaseapp.com',
    storageBucket: 'flutiq.firebasestorage.app',
    measurementId: 'G-4SQ732N25E',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABkxD0aOLF0oUqCLOBe8RaP_6xf16urpA',
    appId: '1:793281383562:web:a0f5b7ebd47e4c070c7173',
    messagingSenderId: '793281383562',
    projectId: 'flutiq',
    authDomain: 'flutiq.firebaseapp.com',
    storageBucket: 'flutiq.firebasestorage.app',
    measurementId: 'G-4SQ732N25E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHaHcmSAyxezmZhxWnzDOa6HUFU4A3l4s',
    appId: '1:793281383562:android:9c78998faa2e9d930c7173',
    messagingSenderId: '793281383562',
    projectId: 'flutiq',
    storageBucket: 'flutiq.firebasestorage.app',
  );
}
